apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    name: worker-deploy
    app: example-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
      app: example-voting-app
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: example-voting-app
    spec:
      containers:
        - name: worker
          image: kodekloud/examplevotingapp_worker:v1 
    