apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: worker-pod
    app: example-voting-app
spec:
  containers:
    - name: worker
      image: kodekloud/examplevotingapp_worker:v1